### ISSUE TITLE
Attackers: Movement, Controls and Animations

### ISSUE THREAD

**Issue by lawlbit** [lawlbit/GameNamePlaceHolder#10]
- **(DONE)** Hero movement & controls
- **(DONE)** Susan: Hero attacks

**DEADLINE:** October 28, 2018 @ 11:59pm

**Comment by SusanSuY** [comment]
Fully integrated hero movement & controls. Updated hero camera.

**Comment by SusanSuY** [comment]
Integrated hero health and combat.
