### ISSUE TITLE
SUGGESTION: Fix "Roar" Description

### ISSUE THREAD

**Issue by David-Hobson** [lawlbit/GameNamePlaceHolder#101]
In the description of "Roar" it says "To damage all creatures near you. Near you." The second "near you" shouldn't be there.

**Comment by SusanSuY** [comment]
Fixed in commit [a62232b](https://github.com/lawlbit/GameNamePlaceHolder/commit/a62232b503b373a4a8f7e4f12aef333549018aa3). Removed the second "near you".
