### ISSUE TITLE
ISSUE #6: Provide a mini-map

### ISSUE THREAD

**Issue by JohnnyEndrizzi** [lawlbit/GameNamePlaceHolder#112]
Provide a map or some other way for players to orient themselves.  Without one, it is very difficult to find places you need to go or have already been.

If the map is intended to be a maze then the mini-map can be blank (no walls) to at least give a sense of where in the world you are.  

Alternatively you could allow the player to uncover the map as they go to encourage exploration at the start.

**Comment by SusanSuY** [comment]
Thanks for the suggestion, but we won't be adding one as it creates another layer of difficulty to the game.
