### ISSUE TITLE
Issue: "Create Dungeon" is not capitalized.

### ISSUE THREAD

**Issue by nicolaikozel** [lawlbit/GameNamePlaceHolder#127]
Small issue that can be fixed easily. It appears that "Create Dungeon" is not all capitalized unlike the rest of the text in the menu options. This format should be kept consistent one way or the other.

**Comment by SusanSuY** [comment]
Fixed in commit [7bc115f](https://github.com/lawlbit/GameNamePlaceHolder/commit/7bc115f900842cc9f8621ae5e5ca42cbd537678f)
