### ISSUE TITLE
Suggestion: Skill Distribution Changes

### ISSUE THREAD

**Issue by nicolaikozel** [lawlbit/GameNamePlaceHolder#130]
The issues I noticed with the skill point distribution is that there is no way to reset the distribution, there is no indication of which characters excel at which attributes, and it is not obvious what the default distribution is. To fix this, I suggest doing the following.

1.  Add a button "Reset" to remove all user allocated skill points and set the distribution back to default.
2. Have different distributions per character type. (i.e wizard has a higher magic vs physical etc) This will help with typing and what characters are better than others at certain things.
3. Grey out the minus skill point arrow if already at the default. I.e if default physical damage is 10, then if at 10 the minus arrow should be grayed out so user knows they can't subtract anymore from that category.

**Comment by SusanSuY** [comment]
We have decided to remove stat allocation, so this issue is now irrelevant.
