### ISSUE TITLE
Issue: Skill Selection 

### ISSUE THREAD

**Issue by nicolaikozel** [lawlbit/GameNamePlaceHolder#131]
No way to re-arrange skills once they are selected. Also no feedback to indicate that a skill has already been selected.

**Comment by SusanSuY** [comment]
Feedback issue addressed in commit [f3a38c9](https://github.com/lawlbit/GameNamePlaceHolder/commit/f3a38c96193256d8340cd519bb2373d638883d06). Equipped skills are now faded out in the skill bank, and are not draggable.
