### ISSUE TITLE
Issue: 2nd Player's stat distribution doesn't add or subtract properly. 

### ISSUE THREAD

**Issue by nicolaikozel** [lawlbit/GameNamePlaceHolder#133]
Following this issue - https://github.com/lawlbit/GameNamePlaceHolder/issues/103#issue-395370462.
As David mentions, the stats reset from 0 to the default numbers after trying to add one but then the adding and subtracting doesn't work. (Adding will subtract, and subtracting will add).

**Comment by SusanSuY** [comment]
Duplicate of issues #58 , #59
