### ISSUE TITLE
SUGGESTION #2: Allow num pad keys to be used for skills

### ISSUE THREAD

**Issue by SullivanStobo** [lawlbit/GameNamePlaceHolder#138]
I'm left handed, so I prefer using the arrow keys rather than wsad, so I appreciate that you allowed movement via arrow keys. However, using arrow keys it is impossible to reach across the key board to press the skill hot keys as they are. This could be solved by allowing num pad number to used as well, or just making them rebindable.

**Comment by SusanSuY** [comment]
Similar suggestion to issue #70
