### ISSUE TITLE
SUGGESTION #4: Clicking and dragging to add skills would be more intuative

### ISSUE THREAD

**Issue by SullivanStobo** [lawlbit/GameNamePlaceHolder#140]
This would also allow for easier reordering of skills if a different order is preferred.

**Comment by sma7560** [comment]
Since skills can be rearranged by unequipping and re-equipping, this is a low priority for us.

**Comment by SusanSuY** [comment]
Added in commit [f14d522](https://github.com/lawlbit/GameNamePlaceHolder/commit/f14d522273cf62e6d2f113629b3742214c824c01).
