### ISSUE TITLE
Issue: Graphics Options Limited

### ISSUE THREAD

**Issue by pavlearezina** [lawlbit/GameNamePlaceHolder#157]
Graphics Option only allows one screen resolution and one video settings which is high. Does not let user change the options to a lower quality or different resolution.

**Comment by sma7560** [comment]
Dupe of #57

**Comment by sma7560** [comment]
We will likely remove the in-game graphics menu.

**Comment by SusanSuY** [comment]
In-game graphics menu has been removed in commit [09abbcd](https://github.com/lawlbit/GameNamePlaceHolder/commit/09abbcdd390f11980b536d3a49ca0725645b8dee)
