### ISSUE TITLE
Suggestion: Remove Network Settings

### ISSUE THREAD

**Issue by pavlearezina** [lawlbit/GameNamePlaceHolder#158]
Currently the network settings only have the ip address that is already posted on the main character selection screen. If nothing else will be added here then this section is redundant, most network settings should be handled before the game is created, not a lot can change when the host is created already with predefined parameters.

**Comment by SusanSuY** [comment]
Fixed in commit [09abbcd](https://github.com/lawlbit/GameNamePlaceHolder/commit/09abbcdd390f11980b536d3a49ca0725645b8dee)
