### ISSUE TITLE
Issue: Wrong statement when creating game

### ISSUE THREAD

**Issue by pavlearezina** [lawlbit/GameNamePlaceHolder#159]
When creating dungeons it states that you join the forsaken but in reality you are being the seekers that clear the dungeon.

**Comment by sma7560** [comment]
Good catch, thanks. We'll have that fixed.

**Comment by SusanSuY** [comment]
Fixed in commit [7bc115f](https://github.com/lawlbit/GameNamePlaceHolder/commit/7bc115f900842cc9f8621ae5e5ca42cbd537678f)
