### ISSUE TITLE
Update Functional Requirements

### ISSUE THREAD

**Issue by SusanSuY** [lawlbit/GameNamePlaceHolder#16]
There are still missing functional requirements; please add them.

Some missing functional requirements include:
1. **FINISHED**: Menu: Join Match
2. **FINISHED**: Attacker - In-Game Mechanics: attackers will lose HP when injured by an obstacle.
3. **FINISHED**: Attacker - In-Game Mechanics: attackers spawn with full HP of 100 health points.
4. **FINISHED**: Attacker - In-Game Mechanics: Health can be recovered through use of items.
5. **FINISHED**: Attacker - In-Game Mechanics: requirements on hero statistics (what are the statistics that heroes will have? What will be displayed when we open the hero statistics window?)
6. **FINISHED**: Defender - Deck Mechanics: "A defender's card must either be a minion, curse, or trap card." Please change this to include cards affecting final boss character (ie. cards obtained that will translate to a skill for the final boss character, buffs for final boss character, etc.)
7. Add resource generation functional requirements. We don't have anything for this yet.
8. **FINISHED**: Primary Gameplay Mode - System will connect all players through LAN network connection.
9. Add some more defender boss requirements if you can think of some.
10. **FINISHED**: Primary Gameplay Mode - the map will have multiple paths from the spawn point to the destination.

**Comment by Codhog** [comment]
the changes on 1 2 3 4 5 6 is done someone please kindly finish.
