### ISSUE TITLE
Suggestion: Number of max players

### ISSUE THREAD

**Issue by pavlearezina** [lawlbit/GameNamePlaceHolder#160]
There is no statement which shows the maximum allowable number of players, this would be an issue for networking reasons where more players makes the lag worse and game balance reasons where more players might unbalance the game.

**Comment by SusanSuY** [comment]
Added in commit [34658e4](https://github.com/lawlbit/GameNamePlaceHolder/commit/34658e424fda3002d913d9ce57724075a8a3890f).
