### ISSUE TITLE
SUGGESTION: Q and E Item Boxes are hard to see when on black background

### ISSUE THREAD

**Issue by wildingelijah** [lawlbit/GameNamePlaceHolder#175]
#### Context
This is a quality of life suggestion. The feature isn't broken as it is but there are certain instances where it can be hard to see everything precisely.

#### High Level Suggestions
Suggestions include changing colours of either the background (specifically when item boxes align or just in general) or changing the item boxes (again either when over the black background or just in general).

### Rationale
This would be to make the game easier to understand and ensure that all features are usable at all times.

**Comment by SusanSuY** [comment]
Removed Q and E
