### ISSUE TITLE
Visual Design: UI

### ISSUE THREAD

**Issue by lawlbit** [lawlbit/GameNamePlaceHolder#19]
- **(DONE)** Susan: Menu UI
- **(DONE)** Simon: Basic Defender UI (cards, energy bar, mini-map, etc.)
- **(DONE)** Susan: Basic Attacker UI (skills and other on-screen elements during dungeon crawling phase)

**DEADLINE:** October 27, 2018 @ 11:59pm

**Comment by SusanSuY** [comment]
Menu UI (main menu + in-game menu) already done. Basic attacker UI also done (added as prefab to Menu^UI Prefab folder).

**Comment by sma7560** [comment]
Completed basic Defender UI and added as prefab, mini-map and cards to be implemented for future milestone.
