### ISSUE TITLE
Game Flow: Phases

### ISSUE THREAD

**Issue by lawlbit** [lawlbit/GameNamePlaceHolder#23]
- **(DONE)** Game stage changes from pre-phase -> dungeon phase
- **(IN PROGRESS)** Game stage changes from dungeon phase -> victory phase
- **(DONE)** Ensure game flows between phases smoothly
- **(DONE)** Ensure game state is not compromised due to networking status

**DEADLINE**: December 18, 2018 @ 11:59pm

**Comment by SusanSuY** [comment]
Pre-phase added to game, which leads to dungeon phase after all players connected + countdown is over. Still need to carry over some information to dungeon after pre-phase.

**Comment by SusanSuY** [comment]
Stats correctly carry over from pre-phase -> dungeon. Still waiting for skills to be implemented to carry that over as well. Also need the victory screen to check dungeon -> victory screen flow. Will work on fixing bugs in game state with disconnected clients/server.

**Comment by SusanSuY** [comment]
Added some logic to catch case where client disconnects.

**Comment by SusanSuY** [comment]
Need to check that victory screen works
