### ISSUE TITLE
Requirements Doc: PUC Rework

### ISSUE THREAD

**Issue by lawlbit** [lawlbit/GameNamePlaceHolder#24]
Edit PUC to reflect new scope.

**Tasks**:
- **(NOT DONE)** Remove "unlock skills" related PUCs
- **(NOT DONE)** Remove "Transition Between Levels" (we now only have one level)

**DEADLINE:** February 12, 2019 @ 11:30pm

**Comment by SusanSuY** [comment]
Reminder to finish this task for next milestone (due on February 12)
