### ISSUE TITLE
Implement score system

### ISSUE THREAD

**Issue by SusanSuY** [lawlbit/GameNamePlaceHolder#38]
Implement the scoring system
- **(DONE)** Add basic code for scores (ie. increaseScore(), getScore(), etc.)
- **(DONE)** Attach score to each player of the game
- **(DONE)** Integrate scoring into UI
- **(SIMON & THIEN - NOT DONE)** Ensure that score increases upon the player performing actions that should reward them (ie. kill minion, collect artifact, complete objective, etc.)

**DEADLINE:** December 18, 2018 @ 11:59pm

**Comment by SusanSuY** [comment]
Please update this issue with the current status.

**Comment by sma7560** [comment]
Scoring added, score increments with every artifact returned.
