### ISSUE TITLE
Implement Artifacts

### ISSUE THREAD

**Issue by SusanSuY** [lawlbit/GameNamePlaceHolder#39]
Integrate artifacts into the game
- **(DONE, NEED TESTING)** Create prefab for artifacts
- **(NOT DONE)** Spawn artifacts randomly (also considering fairness) on the map
- **(DONE, NOT YET USED)** Make sure artifacts have a price attached to them (score that players will gain upon collecting it); as the game progresses, price of artifacts also increases

**DEADLINE:** December 18, 2018 @ 11:59pm

**Comment by SusanSuY** [comment]
Please update this issue with the current status.

**Comment by sma7560** [comment]
Implemented spawning objectives, objective dropping, and scoring.
