### ISSUE TITLE
Bug Report #4: Player 1 was able to kill the square that was spawn trapping Player 2 without taking any damage as the square never targeted player 1

### ISSUE THREAD

**Issue by zpalantz** [lawlbit/GameNamePlaceHolder#48]
Player 1 was able to kill the square that was spawn trapping Player 2 without taking any damage as the square never targeted player 1.

**Comment by SusanSuY** [comment]
Fixed in commit [3193c7b](https://github.com/lawlbit/GameNamePlaceHolder/commit/3193c7ba0f098bd06e614d8d184880317a945fd8).
