### ISSUE TITLE
Bug #3: Graphics setting is not included in main setting panel, but it is included in game.

### ISSUE THREAD

**Issue by TinkLyke** [lawlbit/GameNamePlaceHolder#57]
Graphics setting is not included in main setting panel, but it is included in game.

**Comment by SusanSuY** [comment]
The graphics setting in-game is likely to be removed.

**Comment by SusanSuY** [comment]
In-game graphics setting removed in commit [09abbcd](https://github.com/lawlbit/GameNamePlaceHolder/commit/09abbcdd390f11980b536d3a49ca0725645b8dee).
