### ISSUE TITLE
[Damian] ISSUE #5: Gameplay continue after Game Over

### ISSUE THREAD

**Issue by DamianAngelone** [lawlbit/GameNamePlaceHolder#69]
**Description**
Gameplay will continue after a Game Over. This includes movement, spells, picking up artifacts, and dying again.

**Steps to Reproduce**
- Run out of time
- Achieve a Game Over
- Note that all the actions listed above are possible

**Appearance of Bug**
The multiple times I achieved Game Over my character was able to perform normally as if it didn't happen.

**Suggested Solutions**
An easy fix for this is setting a flag upon achieving Game Over that will prevent the character's Update functions from working anymore. This flag can be reset upon starting a new attempt.

**System Configuration**
- Game tested as windowed (1280 x 600)
- OS: Microsoft Windows 10 (Version 10.0.17134)
- Tested on Laptop: 8GB RAM, Intel Core i5-4210U, 1.70GHz 
- Controller: Laptop's QWERTY Keyboard

**Comment by SusanSuY** [comment]
Fixed in commit [da1fd35](https://github.com/lawlbit/GameNamePlaceHolder/commit/da1fd359025d4919d090603c9ef0508d08010954)
