### ISSUE TITLE
[Damian] ISSUE #8: Artifact can fall out of bounds after death

### ISSUE THREAD

**Issue by DamianAngelone** [lawlbit/GameNamePlaceHolder#72]
**Description**
If you are near a boundary, dying will drop the artifact outside of bounds. Walking close to the boundary allows the artifact to be picked up again.

**Steps to Reproduce**
- Locate an artifact
- Obtain the artifact
- Position your character to right up against a wall
- Have the other player kill you
- Note that the artifact falls out of bounds, beyond the wall
- Walk back to your death location
- Note that you can reobtain the artifact from out of bounds

**Appearance of Bug**
This bug doesn't occur all the time, only the times where the drop position of the artifact upon death randomly chooses the position beyond the wall.

**Suggested Solutions**
This can be fixed by dropping the artifact exactly where the character was standing at death, not accounting for any forward momentum the player may have had. With a proper collider setup on the artifact, it shouldn't be able to clip through the walls.

**System Configuration**
- Game tested as windowed (1280 x 600)
- OS: Microsoft Windows 10 (Version 10.0.17134)
- Tested on Laptop: 8GB RAM, Intel Core i5-4210U, 1.70GHz 
- Controller: Laptop's QWERTY Keyboard

**Comment by Chaozs** [comment]
Should be fixed with d70ecbe73bfdf66d00b16fe040857f6a062e5833
