### ISSUE TITLE
ISSUE #2: Attacked by enemies, but players take no damage.

### ISSUE THREAD

**Issue by FrankYang1995** [lawlbit/GameNamePlaceHolder#76]
In some case, square enemies collide with players, but player’s health is not decreased at all.
<img width="960" alt="enemynodmg" src="https://user-images.githubusercontent.com/17149729/50379098-66c46800-060d-11e9-8efd-0a7c42d9a1d5.png">

**Comment by SusanSuY** [comment]
Seems I cannot reproduce anymore after testing with a change to enemy targetting AI (done in commit [3193c7b](https://github.com/lawlbit/GameNamePlaceHolder/commit/3193c7ba0f098bd06e614d8d184880317a945fd8)).
