### ISSUE TITLE
ISSUE #3: Incorrect display when over two players. 

### ISSUE THREAD

**Issue by FrankYang1995** [lawlbit/GameNamePlaceHolder#77]
If there are more than two players connecting the dungeon, the third player will standing on the head of second player. In addition, “Number of player connected” is still two
<img width="960" alt="threeplayers" src="https://user-images.githubusercontent.com/17149729/50379112-0f72c780-060e-11e9-8a84-f04e15e2b4dc.png">
.

**Comment by SusanSuY** [comment]
Currently, the game only supports max 2 players. We need to add a cap on the number of players who can connect to the game.

**Comment by SusanSuY** [comment]
Fixed in commit [2a42f06](https://github.com/lawlbit/GameNamePlaceHolder/commit/2a42f063da483dede28a06820cb5c6470da5dec2). Capped the number of connections to 2 players max.
