### ISSUE TITLE
ISSUE #4: Incorrect display when one of the Player respawns after death.

### ISSUE THREAD

**Issue by FrankYang1995** [lawlbit/GameNamePlaceHolder#78]
Player 1 is "King", he killed player 2, "mage". After player 2 respawns, the character is still “mage” in player 2’s screen; but the character becomes king in player1’s screen.
<img width="960" alt="playerrespawn" src="https://user-images.githubusercontent.com/17149729/50379140-f880a500-060e-11e9-8769-9172b224f637.png">
<img width="960" alt="playerrespawn2" src="https://user-images.githubusercontent.com/17149729/50379141-f880a500-060e-11e9-94ea-f4ba934d9f41.png">

**Comment by SusanSuY** [comment]
Fixed in commit [c923b6e](https://github.com/lawlbit/GameNamePlaceHolder/commit/c923b6e8b7ab9ad944225b9c42a1d04b1e82f48d). Models are now properly synced across all players.
