### ISSUE TITLE
ISSUE #6: No way to earn scores. 

### ISSUE THREAD

**Issue by FrankYang1995** [lawlbit/GameNamePlaceHolder#80]
Players cannot earn scores by killing other players, killing enemies, collecting artifact. Like the picture, no scores after killing other player.
<img width="960" alt="noscore" src="https://user-images.githubusercontent.com/17149729/50379191-d556f500-0610-11e9-94b3-68fb80d40369.png">

**Comment by SusanSuY** [comment]
We will add instructions/tutorial to explain how to gain score. Currently, score cannot be gained from killing anything, and only from collecting artifacts (need to pick it up, then return to spawn point like "capture the flag"), and from completing objectives (not yet implemented).
