### ISSUE TITLE
ISSUE #7: One player disconnects will cause other players disconnected

### ISSUE THREAD

**Issue by FrankYang1995** [lawlbit/GameNamePlaceHolder#81]
If one of the player disconnect from the match, all other players will be disconnected from the match. One player's action should not affect other players. In addition, it should display scoreboard before disconnected from the match

**Comment by SusanSuY** [comment]
The disconnection is intentional as the match cannot go on without all players, but we will add an error message upon disconnection to explain what has happened.

**Comment by SusanSuY** [comment]
Linked to issue #44
