### ISSUE TITLE
ISSUE #8: Moving control improvement while player’s character collides with wall. 

### ISSUE THREAD

**Issue by FrankYang1995** [lawlbit/GameNamePlaceHolder#82]
If there is a wall in the left of the character, player cannot move the character by clicking “A+S” or “A+W”. The control could be improved If the system allows player moving down or up by clicking “A+S” or “A+W” even though there is obstacle in the left.

**Comment by SusanSuY** [comment]
Thank you for the suggestion, but we will decide to keep movement the way it is.
