### ISSUE TITLE
Ability Framework

### ISSUE THREAD

**Issue by lawlbit** [lawlbit/GameNamePlaceHolder#9]
Main goal: layout the framework for abilities

- Design basic abilities
- Design baseline mechanics (including stats)

**DEADLINE:** December 18, 2018 @ 11:59pm
**!! MUST** have the basic framework laid out by this date, and at least 4 unique (basic) skills implemented.

**Comment by SusanSuY** [comment]
Not completely necessary for Demo #1 so I removed it as the milestone. Need to focus on attacker object working first.

**Comment by lawlbit** [comment]
Currently no animations in place, need to get assets first. Will start working on a template for building skills.
